# Generated by Django 6.0.1 on 2026-01-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='topic',
            new_name='entry',
        ),
    ]
